//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int id { get; set; }
        public int course_id { get; set; }
        public string title { get; set; }
        public string overview { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string updated_by { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
